# Maximum number of concurrent connections to devices
MaxSimultaneousConn = 300

# Data directory, don't change this unless you know what you're doing
DataDir = "data"

# Minimum log level to display on Dashboard
DashboardLogLevel = "Warning"

[server]
# Address to bind server (keep blank unless you know what you're doing)
BindAddress = ""

# Port to bind
BindPort = 8080

[database]
Address = "localhost"
Port = 3306
Username = "root"
Password = "a"
Name = "inca_data"
