# Maximum number of concurrent connections to devices
# MaxSimultaneousConn = 1000

[credentials]
# Username and password to login to device
RemoteUsername = ""
RemotePassword = ""

# Enable password for Cisco devices
EnablePassword = ""

[paths]
# DeviceList  = "config/device-definitions.conf"
# DeviceTypes = "config/device-types.conf"
# ConfDir     = "latest"
# ScriptDir   = "scripts"
# ArchiveDir  = "archive"

[server]
# Address to bind server (keep blank unless you know what you're doing)
# BindAddress = ""

# Port to bind
# BindPort = 8080

[hooks]
# PreScript = ""
# PostScript = ""
